# assembling front matter
# assumes that all files exist but size 0 if not available for book
cat \
"$TMPDIR$uuid/titlepage.md" \
"$TMPDIR$uuid/robo_ack.md" \
"$TMPDIR$uuid/settings.md" \
"$TMPDIR$uuid/rebuild.md" \
"$TMPDIR$uuid/tldr.md" \
"$TMPDIR$uuid/listofpages.md" \
"$TMPDIR$uuid/humansummary.md" \
"$TMPDIR$uuid/programmaticsummary.md" \
"$TMPDIR$uuid/add_this_content.md" \
"$TMPDIR$uuid/content_collections/content_collections_results.md" \
"$TMPDIR$uuid/chapters.md" \
"$TMPDIR$uuid/search_engine_content.md" \
"$TMPDIR$uuid/googler.md" \
"$TMPDIR$uuid/googler-news.md" \
"$TMPDIR$uuid/sorted_uniqs.md" \
"$TMPDIR$uuid/analyzed_webpage.md" \
"$TMPDIR$uuid/acronyms.md" \
"$TMPDIR$uuid/twitter/sample_tweets.md" \
"$TMPDIR$uuid/allflickr.md" \
"$TMPDIR$uuid/sources.md" \
"$TMPDIR$uuid/changelog.md" \
"$TMPDIR$uuid/builtby.md" \
"$TMPDIR$uuid/byimprint.md" \
"$TMPDIR$uuid/imprint_mission_statement.md" \
"$TMPDIR$uuid/yaml-metadata.md" \
> "$TMPDIR$uuid/complete.md"
