echo "reporting values of variables after setup" | tee --append $sfb_log
echo "rows is" $rows 
echo "price is" $price 
echo "categoryid is" $categoryid 
echo "seedfile is" $seedfile 
echo "userid is" $userid 
echo "customtitle is" $customtitle 
echo "endurl is" $endurl 
echo "coverfile is" $coverfile 
echo "fetchfile is" $fetchfile 
echo "special_lasts_minutes is" $special_lasts_minutes 
echo "special_price is" $special_price 
echo "covercolor is" $covercolor 
echo "coverfont is" $coverfont 
echo "covertype_id is" $covertype_id 
echo "coverbase is" $coverbase 
echo "coverfontcolor is" $coverfontcolor 
echo "coverRGB is" $coverRGB 
echo "text_extraction_on is" $text_extraction_on 
echo "refresh is" $refresh 
echo "editedby is" $editedby 
echo "seedsource is" $seedsource 
echo "breaking is" $breaking 
echo "editorid is" $editorid 
echo "singleseed is" $singleseed 
echo "import is" $import 
echo "mylibrary is" $mylibrary 
echo "fleet is" $fleet 
echo "booktype is" $booktype 
echo "ebookformat is" $ebookformat 
echo "fetched_document_format is" $fetched_document_format 
echo "verbose is" $verbose 
echo "userdescription is" $userdescription 
echo "pass_uuid is" $pass_uuid 
echo "ISBN_assign_automatically" is $ISBN_assign_automatically 
echo "ISBN is" $ISBN 
# echo "ISBN_owner is" ) 
echo "jobprofile is" $jobprofile 

