abstracts="both"
add_corpora="no"
add_imprint_biblio="yes"
add_this_content_part_name="User-Provided Content"
add_this_content="none"
analyze_url="no"
angbr="<"
arxiv="no"
attribute_set="Default"
authorphoto="authorphoto.png"
backmatter="on"
BISAC_code="None"
body="<body>"
bold="<b>"
booktitle="Book by PageKicker"
booktype="Reader"
booktypewebformid='"/item/booktype"'
breaking="no"
build_all_formats="yes"
build_bw_pdf="yes"
build_color_pdf="yes"
build_docx="no"
build_linkrich_epub="yes"
build_mobi="yes"
build_text_epub="yes"
build_txt_html_only="no"
builder="yes"
buildtarget="$mediatargetpath"
categories="4"
categoryid=2
closeparen=")"
cover_image_extension=".png"
coverbase="images/bottomcanvas.png"
covercolor="black"
coverfile="assets/NCP-cover.jpg"
coverfont="TitilliumWeb"
coverfontcolor="white"
coverRGB="0,0,0"
covertype_id="1"
customer_email="store@pagekicker.com"
customeridwebformid='"/item/customerid"'
customtitle="none"
dedicationfilename="default.html"
dedicationfilename="default.html"
description="test"
docsandabstracts="'<b>Document titles and abstracts:</b><p>'"
docxlinkname="Microsoft_Word_docx"
docxname="Microsoft_Word_docx"
dontcleanupseeds="no"
dq='"'
ebookformat="epub"
ebookintro="includes/ebook.intro.html"
editedby="PageKicker"
editorid="1"
endanchor="/a>"
endbody="</body>"
endbold="</b>"
endbr=">"
endhead="</endhead>"
endhtml="</html>"
endp="</p>"
endurl="&prop=links&pllimit=500&format=xml"
epub=".epub"xmlstarletwebformstart="xmlstarlet sel -t -v"
epublinkname="ePub"
epublinkrichname="Pub"
exemplar_file="none"
exemplar_filedir_code=400 # this is the field code value used in the directory structure where magento webforms stores uploaded exemplar files -- softcoded below
expand_seeds_to_pages="no"
fb_announcement="no"
fetcharray=()
fetched_document_format="html"
fetchfile="fetch/fetchlist.csv"
firstname=""
fleet="yes"
flickr="no"
flickr="off"
frontmatter="on"
h1=$angbr"h1"$endbr
h1end=$angbr$slash"h1"$endbr
h2=$angbr"h2"$endbr
h2end=$angbr$slash"h2"$endr
h3=$angbr"h3"$endbr
h3end=$angbr$slash"h3"$endbr
head="<head>"
html="<html>"
httpvalidate='(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
imgsrc="<IMG SRC="
import="no"
imprint="pagekicker"
ISBN_assign_automatically="no"
ISBN_owner="0"
ISBN="012345679X"
jobprofilename="default"
lastname=""
LSI_import="yes"
mailtofred="yes"
maximages="4" #default
middlename=""
mobilinkname="Kindle"
montageur="off"
montageurdir="montageur"
mylibrary="yes"
nameprefix=""
negative_seed_weight=1
negative_seeds=""
newline="/n"
news_lasts_minutes="43200"
news_to_buffer="2592000"
on=" on "
openanchor="<a href="$dq
openparen="("
outfile="montage.jpg"
p="<p>"
pass_uuid="no"
pdflinkname="PDF"
pdfserif="MinionWebPro"
pipe="|"
positive_seed_weight=1
positive_seeds=""
price=0.99
printconfigfile="yes"
refresh="yes"
robot_summary_length=10
rows=1
sample_tweets="no"
seedfile=""
seedsource="PageKicker"
SEOmodule_status="off"
seriesdescriptionfilename="default.html"
shortform="no"
singleseed=""
singleseedwebformid='"/item/singleseed"'
sku=`tail -1 < "$LOCAL_DATA""SKUs/sku_list"`
slash="/"
slidebodyfont="ACaslonPro-Semibold"  #Decimator
special_lasts_minutes="43200"
special_price="0"
special_to_buffer="2592000"
specialstoreid="0"
sq="'"
status="Enabled"
stopimagefolder="none" #default
storecode="admin"
storeids="0"
subtitle=""
summarizer_ngram_threshold=2
summarizer_on=Y
summary_length=10
summary="both"
text_extraction_on="yes"
thumbxsize=120 #default
thumbysize=120 #default
tldr=""
top_q="20" # number of nerv lines used divided by 2
toplabelfont="WatersTitlingPro-Bd" #  #Decimator must be available font
toplabelfontname="WatersTitlingPro-Bd" #Decimator
txtformatname=".txt"
txtwildcard="*.txt"
twitter_announcement="no"
type="downloadable"
userdatadir="none"
userdescription="no"
userid="1"
userlogo="assets/imprint.png"
verbose="no"
visibility="Catalog,Search"
websites="base"
wikilocale="en"
wordcount=0
wordcountpages=0
wordcountsummaries=0
x="x" # for imagemagick scripts
xmlstarletwebformstart="xmlstarlet sel -t -v"
xpathwebformid='"/item/webform_id"'
yourname="no"
